// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etfcwurzgcejycgkruuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZmN3dXJ6Z2NlanljZ2tydXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE1ODcsImV4cCI6MjA2NTQ5NzU4N30.4MmZzbC6Bpz1o0sKg86lhazOwGFTzKkdZbEreH2ai0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);